# Generated by Django 4.2.3 on 2023-07-12 06:50

from django.db import migrations

def create_data(apps, schema_editor):
    Guide = apps.get_model('quranic_verses', 'Guides')
    Guide(name="Book", description="A book for quranic verse").save()


class Migration(migrations.Migration):

    dependencies = [
        ('quranic_verses', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
