# Generated by Django 4.2.3 on 2023-08-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranic_verses', '0004_alter_guides_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guides',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
    ]
