# Generated by Django 4.2.3 on 2023-08-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quranic_verses', '0008_guidetopic_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='question')),
                ('answer_1', models.CharField(max_length=200, verbose_name='answer 1')),
                ('answer_2', models.CharField(max_length=200, verbose_name='answer 2')),
                ('answer_3', models.CharField(max_length=200, verbose_name='answer 3')),
                ('answer_4', models.CharField(max_length=200, verbose_name='answer 4')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='correct answer')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quranic_verses.guidetopic')),
            ],
        ),
    ]
