# Generated by Django 4.2.3 on 2023-08-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranic_verses', '0009_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='note'),
        ),
    ]
