# Generated by Django 4.2.3 on 2023-08-24 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quranic_verses', '0010_quizquestion_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('time_taken_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quranic_verses.guidetopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_taken_at'],
            },
        ),
    ]
