# Generated by Django 4.2.3 on 2023-08-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranic_verses', '0011_userquizprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceField', models.CharField(choices=[('choice1', 'Freshman'), ('choice2', 'Sophomore'), ('choice3', 'Junior'), ('choice4', 'Senior')], max_length=200)),
            ],
        ),
    ]
