# Generated by Django 4.2.3 on 2023-09-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranic_verses', '0013_guidecontent_delete_testchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='guidecontent',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='content'),
        ),
    ]
