# Generated by Django 4.2.3 on 2023-09-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranic_verses', '0016_usersavedverse_saved_usersavedverse_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedverse',
            name='translation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='verse translation'),
        ),
    ]
